# Setup
title:        ğŸ˜ˆå¼ èµ·çµ
tagline:      æˆ‘æ˜¯ä¸€ä¸ªå˜æ€
baseurl:      ""
paginate:     1
locale:       "cn"

# About/contact
author:
  name:       èµµç”³ä¾ƒ
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown